"""
Train the Random Forest Regressor on skin feature data.

Run once before starting app.py:
    python train_model.py

Note: texture_score in the CSV was generated by the previous 1D gradient algorithm.
After re-running feature extraction on original images with the updated LBP algorithm,
regenerate the CSV and re-run this script to update the model.
"""

import os
import pickle
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import MinMaxScaler

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
CSV_PATH = os.path.join(BASE_DIR, 'skin_features_dataset.csv')
MODEL_PATH = os.path.join(BASE_DIR, 'rf_model.pkl')
SCALER_PATH = os.path.join(BASE_DIR, 'scaler.pkl')

# Clinical weights for auto-labelling:
# pigmentation (dark pixel coverage) is the strongest UV damage indicator,
# followed by spot count, then texture complexity.
WEIGHTS = {'pigmentation': 0.50, 'spot_count': 0.35, 'texture_score': 0.15}

def generate_labels(df: pd.DataFrame) -> pd.Series:
    spot_max = df['spot_count'].max()
    texture_max = df['texture_score'].max()
    pig_max = df['pigmentation'].max()

    spot_norm = (df['spot_count'] / spot_max).clip(0, 1)
    texture_norm = (df['texture_score'] / texture_max).clip(0, 1)
    pig_norm = (df['pigmentation'] / pig_max).clip(0, 1)

    return (
        WEIGHTS['pigmentation'] * pig_norm +
        WEIGHTS['spot_count'] * spot_norm +
        WEIGHTS['texture_score'] * texture_norm
    ).round(4)

def train():
    df = pd.read_csv(CSV_PATH)

    missing = df['target_damage_score'].isnull()
    if missing.any():
        print(f"Generating labels for {missing.sum()} unlabelled rows...")
        df.loc[missing, 'target_damage_score'] = generate_labels(df[missing])
        df.to_csv(CSV_PATH, index=False)
        print(f"  Labels saved to CSV.")

    df = df.dropna(subset=['target_damage_score'])
    X = df[['spot_count', 'texture_score', 'pigmentation']].values
    y = df['target_damage_score'].values

    scaler = MinMaxScaler()
    X_scaled = scaler.fit_transform(X)

    model = RandomForestRegressor(n_estimators=100, random_state=42)
    model.fit(X_scaled, y)

    with open(MODEL_PATH, 'wb') as f:
        pickle.dump(model, f)
    with open(SCALER_PATH, 'wb') as f:
        pickle.dump(scaler, f)

    print(f"Model trained on {len(df)} samples.")
    print(f"  Saved: {MODEL_PATH}")
    print(f"  Saved: {SCALER_PATH}")

if __name__ == '__main__':
    train()
